export const INTERACTIVE_AUDIT_COMPOSER_MAX_WIDTH_PX = 1400
export const INTERACTIVE_AUDIT_MESSAGE_MAX_WIDTH_PX = 1280
export const INTERACTIVE_AUDIT_MESSAGE_MAX_WIDTH_PERCENT = 92

export const INTERACTIVE_AUDIT_MESSAGE_MAX_WIDTH = `min(${INTERACTIVE_AUDIT_MESSAGE_MAX_WIDTH_PX}px, ${INTERACTIVE_AUDIT_MESSAGE_MAX_WIDTH_PERCENT}%)`
